---
- name: Update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

# Ensure Docker service is running
- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

# Login to Docker
- name: Login to Docker Hub
  docker_login:
    username: "{{ docker_login_user }}"
    password: "{{ docker_login_password }}"

# Pull Docker images
- name: Pull Frontend Docker image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: Pull Backend Docker image
  docker_image:
    name: "{{ backend_image }}"
    source: pull

# Run Docker containers
- name: Run Frontend container
  docker_container:
    name: stress-frontend
    image: "{{ frontend_image }}"
    state: started
    ports:
      - "3000:3000"

- name: Run Backend container
  docker_container:
    name: stress-backend
    image: "{{ backend_image }}"
    state: started
    ports:
      - "5000:5000"