---
# Stop all running Docker containers
- name: Stop all running Docker containers
  shell: |
    docker stop $(docker ps -aq) || true
  ignore_errors: true

# Remove all Docker containers
- name: Remove all Docker containers
  shell: |
    docker rm $(docker ps -aq) || true
  ignore_errors: true

# Remove all Docker images
- name: Remove all Docker images
  shell: |
    docker rmi $(docker images -aq) || true
  ignore_errors: true

# Pull Docker images
- name: Pull Frontend Docker image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

# Run Docker containers
- name: Run Frontend container
  docker_container:
    name: stress-frontend
    image: "{{ frontend_image }}"
    state: started
    ports:
      - "3000:3000"
